package ut.edu.be_quanlytro.Entity.Enum;

public enum NotificationType {
    INVOICE_CREATED,INVOICE_REMINDER, INVOICE_OVERDUE, ISSUE_CREATED,
    ISSUE_UPDATED, CONTRACT_SIGNED, PAYMENT_APPROVED, PAYMENT_REJECTED,CONTRACT_EXPIRED,CONTRACT_EXTEND,
    DEPOSIT_CANCELLED
}