spring.application.name=BE_QuanLyTro
server.port=8080

spring.profiles.active=dev

# C?u hình k?t n?i MySQL Local (Thay port 3306/3307 và m?t kh?u t??ng ?ng c?a máy b?n)
spring.datasource.url=jdbc:mysql://localhost:3306/QuanLyPhongTro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=151205
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate t? ??ng sinh b?ng cho MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.auditing.enabled=true

# C?u hình Redis ch?y ng?m local
app.redis.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Khóa bí m?t mã hóa JWT (?? dài > 64 ký t? cho thu?t toán HS512)
app.jwt.secretKey=DayLaDoanMaBiMatSieuCapBaoMatDànhChoHeThongQuanLyPhongTroCuaNhomBinh2026